---
title: "Untitled"
output: html_document
---


```{r}
##WORDCLOUD
library(dplyr)
library(readr)
library(tm)
library(SnowballC)
library(RColorBrewer)
library(wordcloud)
cca <- read.csv("co-curricular-activities-ccas.csv")
#Load the data
cca <- data.frame(cca)

#Create the corpus of data
cca.corpus <- Corpus(VectorSource(cca$cca_generic_name))

##Data Cleaning and Wrangling
cca.Clean<-tm_map(cca.corpus, PlainTextDocument)
cca.Clean<-tm_map(cca.corpus,tolower)
cca.Clean<-tm_map(cca.Clean,removeNumbers)
cca.Clean<-tm_map(cca.Clean,removeWords,stopwords("english"))
cca.Clean<-tm_map(cca.Clean,removeWords,"and") 
cca.Clean<-tm_map(cca.Clean,removeWords,"club")
cca.Clean<-tm_map(cca.Clean,removePunctuation)
#cca.Clean<-tm_map(cca.Clean,stripWhitespace)

wordcloud(cca.Clean, min.freq=1, rot.per=0.35, random.order=FALSE, colors=brewer.pal(8,"Dark2"))
```

```{r}
##ggmap visualisation
library(ggplot2)
library(RgoogleMaps)
library(ggmap)
register_google("AIzaSyDLP0JL8Oj1q9PGVn6JWYO0b7DnmBzi1EA")
details <- read.csv("general-information-of-schools.csv",
                    header=TRUE,
                    colClasses = "character")
View(details)
# details$mainlevel_code
# All columns are parsed in as charcter for convenience sake 
#Load the data
#Converting data to data frame
details <- data.frame(details) %>% filter(mainlevel_code %in% "SECONDARY")
# details
# details %>% left_join()
#Attemtping to retrive geocodes from postal code 
locations_df <- mutate_geocode(details,postal_code)
#lon and lat have been added to last columns of locations_df





map <- get_map("Singapore", zoom=11,source="google")
m1 <- ggmap(map,
            base_layer = ggplot(data=locations_df, aes(x=locations_df$lon,
                                                       y=locations_df$lat))) + geom_point(aes(color=zone_code))

# m1
m1


# locations_df

library(htmlwidgets)
saveWidget(m1, file = "m1.html")
```

```{r}
locations_df
```

